### ISSUE TITLE
Check error translations for completeness and correctness

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#1088] opened 2022-04-06 08:27 UTC
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

The error handling on frontend side should contain more details about specific errors.
The frontend errors can also be translated.
Extend the error mapping on frontend side to support all languages and to give hints about a possible solution

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v1.?.?  |
| API             | v1.?.?  |
| Blockchain      | v1.?.?  |
| Export-Service  | v1.?.?  |
| Email-Service   | v1.?.?  |
| Storage-Service | v1.?.?  |

**Comment by galethil** [comment] 2024-03-14 09:39
Duplicate of #991

**Closed by galethil** 2024-03-14 09:39 UTC
Labels: bug, blockchain, api, frontend, storage-service
