### ISSUE TITLE
document upload payload too large error

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#49] opened 2019-03-22 15:30 UTC
In GitLab by @Stezido on Dec 13, 2018, 14:33

If the uploaded document is 100 MB or larger the api throws an error 413 "Payload Too Large".
Note: Error message on frontend is empty!

**Comment by phpai** [comment] 2019-03-22 15:30
In GitLab by @Stezido on Dec 13, 2018, 14:58

changed the description

**Comment by phpai** [comment] 2019-03-22 15:30
In GitLab by @Stezido on Jan 14, 2019, 14:44

created merge request !169 to address this issue

**Comment by phpai** [comment] 2019-03-22 15:30
In GitLab by @Stezido on Jan 14, 2019, 14:44

mentioned in merge request !169

**Comment by phpai** [comment] 2019-03-22 15:31
In GitLab by @Stezido on Jan 16, 2019, 14:45

**Problem**:<br/>
Cannot replicate the exact same issue. Instead the frontend cannot send a payload larger than around 60MB via post in base64-string format.

**Solution**:
1.  add document size limit 50MB and check size when saving into state.
1.  use multipart instead of base64 to support larger document sizes.

**Comment by phpai** [comment] 2019-03-22 15:31
In GitLab by @kevinbader on Feb 25, 2019, 10:54

- api: the limit is already at 100M
- probably Nginx setting?
- probably better to compute the hash client-side, that is, within the browser, instead
- not sure we should accept even larger payloads

**Comment by gonzochic** [comment] 2019-03-26 14:53
Since this is a feature and not a bug -> closing

**Closed by gonzochic** 2019-03-26 14:53 UTC
Labels: wontfix
