### ISSUE TITLE
API: Add additional history items

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#47] opened 2019-03-22 15:30 UTC
In GitLab by @saschak_94 on Dec 10, 2018, 13:48

Currently the history item when the order of the workflowitems change looks like: 
```text
mstein changed the workflowitem ordering 
```

It would be nice to get details about what exactly changed.

**Comment by mathiashoeld** [comment] 2019-04-12 08:00
@kevinbader duplicate of #33?

**Closed** 2019-04-15 06:29 UTC
Labels: feature
