### ISSUE TITLE
UI: Document upload view removes text of previous uploaded files after uploading another file

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#276] opened 2019-05-08 15:12 UTC
Document upload view removes the text of previous uploaded files after uploading another file

Current list:

<img width="325" alt="Bildschirmfoto 2019-05-08 um 17 07 56" src="https://user-images.githubusercontent.com/20185479/57386112-0563f680-71b4-11e9-90f0-8e475cb3d6f8.png">

After upload of another file:

<img width="341" alt="Bildschirmfoto 2019-05-08 um 17 08 15" src="https://user-images.githubusercontent.com/20185479/57386125-08f77d80-71b4-11e9-9eb6-f9236b3b3903.png">

Note: Exiting and reopening the view correctly shows the uploaded files

**Comment by gonzochic** [comment] 2019-05-09 06:41
Duplicate of #268

**Closed by gonzochic** 2019-05-09 06:41 UTC
