### ISSUE TITLE
Change for Developer Setup instruction 

### ISSUE THREAD

**Issue by AsfaSamee** [openkfw/TruBudget#669] opened 2020-12-03 09:23 UTC
**Description**
This are changes for the documentation of Developer Setup.

**Solution**
To simplify the installation you should divide the Document into two parts. The first area is for the installation. And the second area is for starting the project.

**Comment by mayrmartin** [comment] 2021-07-05 09:37
Duplicate of #782

**Closed by mayrmartin** 2021-07-05 09:37 UTC
Labels: documentation
