### ISSUE TITLE
deployment: add load tests and include in ci

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#73] opened 2019-03-22 15:34 UTC
In GitLab by @phpai on Jan 28, 2019, 17:37

To better see the impact of code changes on the performance, we should add load testing to our test suite

**Comment by phpai** [comment] 2019-03-22 15:34
In GitLab by @phpai on Jan 31, 2019, 10:31

changed the description

**Comment by phpai** [comment] 2019-03-22 15:34
In GitLab by @phpai on Jan 31, 2019, 10:32

changed title from **deployment: {-include load test-} in ci** to **deployment: {+add load tests and include+} in ci**

**Comment by mayrmartin** [comment] 2021-07-05 09:19
Duplicate of #835

**Closed by mayrmartin** 2021-07-05 09:19 UTC
Labels: CI/CD
