### ISSUE TITLE
UI: Toggling vertical scrollbar causes background to resize

### ISSUE THREAD

**Issue by SamuelPull** [openkfw/TruBudget#1617] opened 2024-01-17 08:32 UTC
when toggling between table view and card view, and when items (projects, subprojects, worfklowitems) are filtered by search, scrollbar may appear/disappear which causes the background to resize. looks almost like the screen is flashing.

**Comment by pmolnar-dev** [comment] 2024-02-05 12:03
After analysis, this seems to be an expected behaviour in the browser. It could be cosmetically fixed by adding overflow-y: "scroll" into body css, but then we would have vertical scrollbar in the app at all times. Therefore I am closing this issue for time being.

**Closed by pmolnar-dev** 2024-02-05 12:03 UTC
Labels: bug, frontend
